baseURL: 'https://toriwrites.online'
copyright: WTFPL
disqusShortname: toriwrites-online
languageCode: en-us
theme: hugo-theme-willow
title: Tori Writes (Online)

menu:
  main:
    - identifier: webmaster
      name: Webmaster
      url: webmaster
      pre: webmaster.svg
      weight: 1
    - identifier: about
      name: About
      url: about
      pre: about.svg
      weight: 2
    - identifier: projects
      name: Projects
      url: projects
      pre: projects.svg
      weight: 3
    - identifier: blog
      name: Blog
      url: blog
      pre: blog.svg
      weight: 4
    - identifier: contact
      name: Contact
      url: contact
      pre: contact.svg
      weight: 5

params:
  author: Victoria Rodriguez
  wallpaper: /images/win-90s.jpg

  ## 📌 Social Networks
  email: vrodriguezfe@icloud.com
  githubID: nerdalot
  spotifyID: malditoprotozoo
  telegramID: nerdalot
  twitterID: nerdalot
  youtubeID: UCoACZSKfzZcl2fDT1ybaRwA

  ## 📌 Extra Tools
  debug:
    enabled: false
