baseURL: 'https://toriwrites.online'
copyright: MIT
disqusShortname: toriwrites-online
languageCode: en-us
theme: willow
title: Tori Writes (Online)

menu:
  header:
    - name: about
      weight: 0
      url: about
    - name: projects
      weight: 1
      url: projects
    - name: blog
      weight: 2
      url: blog

params:
  author: Victoria Rodriguez
  description: Description
  headerHostname: toriwrites.online
  headerUsername: Tori
  profilePicture: nerdalot--avatar-rainbow.svg

  ## 📌 Social Networks
  email: vrodriguezfe@icloud.com
  githubID: nerdalot
  spotifyID: malditoprotozoo
  telegramID: nerdalot
  twitterID: nerdalot
  youtubeID: UCoACZSKfzZcl2fDT1ybaRwA

  ## 📌 Debugging
  debug:
    enabled: true